### ISSUE TITLE
Difference from Ray?

### ISSUE THREAD

**Issue by LinxiFan** [deepmind/launchpad#1]
Thank you so much for open-sourcing the library. I really appreciate it. 

I'm curious - launchpad's functionality looks very similar to [Ray](https://ray.io/), which also features an RPC-style API and distributed launching. In addition, Ray supports Ray RLlib, just like Launchpad supports Acme. May I ask what are the key differences and advantages to use Launchpad?

**Comment by ddmbr** [comment]
There are quite a few differences. For example, the execution is decentralized (though centralized control could be implemented on top) - Launchpad doesn't provide a runtime by itself. Launchpad also doesn't attempt to track the computation lineage, allowing individual components to use the most efficient fault recovery mechanism (e.g., a learner will recover from a checkpoint, but an actor will simply restart). The `lp.Node` interface is less Python-centric and is designed to work with existing infrastructure flexibly (e.g., the backing service might not be running Python).

We are releasing a paper soon, which should hopefully answer your question better :)

**Comment by LinxiFan** [comment]
Gotcha, thank you so much for your explanation! I look forward to the paper release :D
