### ISSUE TITLE
Run one of the node in the main process

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/launchpad#13]
For launching with multi-process mode, is it possible to launch one of the nodes in the main process where the launchpad program is launched?

My use case is to integrate with logging in Weights and Biases https://wandb.ai/site, where I would like to create the logging context in the main process (to better preserve argv which is captured by W&B in logging my experiment runs). 
For example, I have a script to launch an LP program 
```bash
python scripts/lp_run_impala.py --config.learning_rate=0.001
```
The program would create an LP program to run a distributed IMPALA training. I created a sink node which the actors and learners can send log information to be logged on W&B. I would like W&B to track the command line arguments I supplied to the training script which is `python scripts/lp_run_impala.py --config.learning_rate=0.001`, this is fine when W&B is initialized in the main process. However, since currently the sink node is launched in a separate process and it captures the argv from the worker process which is
```
<python with no main file> --data_file /tmp/tmpv29m1qx5/job.pkl --lp_task_id 0
```

I suspect that doing some sort of dereferencing of the node would solve the problem but I am not entirely sure of the details. I would really appreciate the launchpad maintainers' help in setting this up!

Many thanks in advance.

**Comment by qstanczyk** [comment]
I think you might find [this](https://github.com/deepmind/launchpad/commit/89579f5db7dddfaf1abacf532b84b24c7656e008) change useful. That way you can run one node in the main process while delegate the other nodes to a different process. It will require some changes in your program builder, but should let you do what you want to achieve. You will have to use lp_local_mt launch type for that.

**Comment by ethanluoyc** [comment]
If I understand things correctly about this new colocation, for the example I have here I should do something like:
```
# Node for the logger/sink
program.add_node(lp.CourierNode(Sink))
nodes = []
# Add the learner
nodes.add_node(lp.CourierNode(Learner, ...))
for _ in range(10):
  nodes.append(lp.CourierNode(Actor, ...))
program.add_node(lp.MultiProcessingColocation(nodes))
```
Then I should launch with lp_local_mt, which now globally launches things with multi-threading but the nodes for the original program is grouped as a single thread but are executed with multi-processing underneath. Is this correct?

**Comment by qstanczyk** [comment]
Yes, correct.

**Comment by ethanluoyc** [comment]
Thanks for open-sourcing this!
