### ISSUE TITLE
Compress option is not passing through nodes to courier

### ISSUE THREAD

**Issue by zhongwen** [deepmind/launchpad#15]
Hey LP team, 

There's a helpful option `compress` in courier client

https://github.com/deepmind/launchpad/blob/7879e9009fee8fb32cdd3133aac92e9bbb6554fa/courier/python/client.py#L117

However it seems that when creating the node, we cannot pass this option in.
https://github.com/deepmind/launchpad/blob/master/launchpad/nodes/courier/node.py#L104

Could you please either 
1) point us how to achieve using `compress` in courier client?
2) add **kwargs to the https://github.com/deepmind/launchpad/blob/master/launchpad/nodes/courier/node.py#L104 ?

Thanks a lot

@ddmbr

**Comment by qstanczyk** [comment]
Could you give [set_client_kwargs](https://github.com/deepmind/launchpad/blob/8712653c1318e36ec6c46f0359cb31124eb57fd5/launchpad/nodes/courier/node.py#L41) a try?

**Comment by qstanczyk** [comment]
Please reopen if suggestion doesn't work for you.
