### ISSUE TITLE
Undefined symbol on importing courier

### ISSUE THREAD

**Issue by wookayin** [deepmind/launchpad#18]
How I installed packages:

Python 3.9.7 from anaconda (linux x86_64)

```
tensorflow==2.6.1
dm-launchpad==0.3.1  (or dm-launchpad-nightly)
dm-reverb==0.5.0
```

When trying to import `courier`, I get the following error:

```
.../site-packages/courier/python/py_client.so: undefined symbol: _ZN4absl14lts_2020_09_235MutexD1Ev
```

With dm-launchpad-nightly (as of 11/3/2021)

```
.../site-packages/courier/python/py_client.so: undefined symbol: _ZNK4absl12lts_202103246Status4codeEv 
```

What am I missing? Is it related to tensorflow (nightly) or dm-reverb (nightly) version? I know Google uses "single versioning" where everything is like a nightly, not quite ensuring backward compatibility, but in the open source community it is very difficult to find a set of DM packages in their stable versions that are compatible with one another.

**Comment by wookayin** [comment]
These are external symbols (as per `nm -g site-packages/courier/python/py_client.so`), and can be found in recent versions of tensorflow: Installing `tf-nightly` would make those symbols available. (TF >= 2.7 required).

**Comment by qstanczyk** [comment]
To make sure you have proper versions of packages it is easiest to install TF and Reverb through Launchpad's PIP:
https://github.com/deepmind/launchpad#installation
