### ISSUE TITLE
Question: How to Debug

### ISSUE THREAD

**Issue by KaleabTessera** [deepmind/launchpad#19]
How do you debug launchpad programs? 

I have tried running the single process version of launchpad (`LOCAL_MULTI_THREADING` launchtype) and adding breakpoints to the relevant parts of the program. I can debug the building of the program nodes, but I can't seem to debug what happens in `lp.launch`.

Do I need to dereference and obtain a handle to every node (like done in the tests)?

**Comment by qstanczyk** [comment]
I just gave it a try and adding `pdb.set_trace()` in the node's code works fine - it stops the node during execution of the program as expected. It works for both `LOCAL_MULTI_THREADING` and `LOCAL_MULTI_PROCESSING`. What is the exact setup it doesn't work for you?

**Comment by KaleabTessera** [comment]
@qstanczyk Thanks for the reply! 

So I haven't tried `pdb`. My setup (and probably most other people's) is vscode + python debugging like [this](https://code.visualstudio.com/docs/python/debugging).

**Comment by qstanczyk** [comment]
I see - this is not the setup we use. If you figure out what it takes to make it work in the node we are happy to incorporate the changes. I wonder - does debugging standard Python threads works with this solution (it would be the first step towards figuring out what is wrong).
