### ISSUE TITLE
Remove dataclasses dependency in the wheel for python > 3.6

### ISSUE THREAD

**Issue by mavenlin** [deepmind/launchpad#3]
Having dataclasses on python 3.8 causes the following error
```
AttributeError: module 'typing' has no attribute '_ClassVar'
```
A similar issue is discussed here
https://github.com/pytorch/pytorch/issues/46930

**Comment by qstanczyk** [comment]
Hi @mavenlin, your suggested change is on its way.

**Comment by qstanczyk** [comment]
Change is in

**Comment by mavenlin** [comment]
Thanks, could you also update it on pypi?

**Comment by qstanczyk** [comment]
It will go out with the next release.

**Comment by vicesodan** [comment]
How to solve this issue?
I can't get rid of this error now after installing dataclasses on python 3.9
AttributeError: module 'typing' has no attribute '_ClassVar'

**Comment by qstanczyk** [comment]
Can you share repro steps for this problem? Best with a fresh docker image, so we can easily reproduce it.

**Comment by mavenlin** [comment]
> How to solve this issue? I can't get rid of this error now after installing dataclasses on python 3.9 AttributeError: module 'typing' has no attribute '_ClassVar'

For python > 3.6, dataclasses is inbuilt, there's no need to install extra dataclasses package. You can try uninstall it.
