### ISSUE TITLE
Update launchpad releases

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/launchpad#32]
Hi,
Currently it seems that latest version of launchpad on PyPI is still building against tensorflow~=2.8.0 and an older version of reverb. This prevents user from being able to update to a later reverb version (as well as tensorflow>2.8). Is it possible to release a new version of launchpad that builds against the latest Reverb release version?

Best,
Yicheng

**Comment by ethanluoyc** [comment]
Ping @qstanczyk @jblespiau @tfboyd for more visibility.

**Comment by ddmbr** [comment]
Hi! I'll try to resolve it early next week.

**Comment by ethanluoyc** [comment]
Thanks! @ddmbr

**Comment by hartikainen** [comment]
This would be really useful for me too.

**Comment by ddmbr** [comment]
This has been resolved.

**Comment by hartikainen** [comment]
@ddmbr, I just checked pypi and can't find any releases newer than 22/04/2022 for [dm-launchpad](https://pypi.org/project/dm-launchpad/#history) and 23/03/2023 for [dm-launchpad-nightly](https://pypi.org/project/dm-launchpad-nightly/#history). Should those be up there?

**Comment by ethanluoyc** [comment]
I don't think it's released. I can't seem to reopen this issue. I will create a new one.
