### ISSUE TITLE
Example of how to specify local resources.

### ISSUE THREAD

**Issue by arnupretorius** [deepmind/launchpad#4]
Hi there, thanks for releasing this! Really appreciated :)

I was just wondering, is there perhaps an example for how to specify the local resources for a launch? I can see that `launch` allows for an optional `Dict[str, Any]` to set up the resource configs. I'm guessing here the str keys refer to the nodes in the program but I'm not sure how to specify the "per-node launch configuration" for each node. Would this also be a dictionary, e.g. `{"gpus": 2, "cpus": 4}`? Apologies if there are examples of this that I missed.

**Comment by qstanczyk** [comment]
Hi Arnu, 
local_resources accepts a dictionary of {"node group" -> [PythonProcess](https://github.com/deepmind/launchpad/blob/f591b5931cbba89bc94050a126d86cd1bda312f5/launchpad/nodes/python/local_multi_processing.py#L50) }
