### ISSUE TITLE
Bug with JAX absl flag configuration

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/launchpad#5]
Hi, 

Thanks for the awesome project!

I found the following issue in `dm-launchpad-nightly=0.1.0.dev20210427`
It seems that if I configure jax absl flags in my entry script launchpad will error on launching the program

For a script that looks something like this
```python

# pylint: disable=unused-import
from absl import app, flags
from jax.config import config
import launchpad as lp

FLAGS = flags.FLAGS

def main(_):
  import os
  os.environ['JAX_PLATFORM_NAME'] = 'cpu'

  program = impala_agent.DistributedIMPALA(
      environment_factory=environment_factory,
      # environment_spec=environment_spec,
      network_factory=network_factory,  # lp_utils.partial_kwargs(helpers.make_networks),
      num_actors=1,
      max_actor_steps=int(1e6)).build()
  lp.launch(program,
            lp.LaunchType.LOCAL_MULTI_PROCESSING,
            terminal='current_terminal')

if __name__ == '__main__':
  config.config_with_absl()  # Errors right now
  app.run(main)  # pylint: disable=no-value-for-parameter
```
This will gives an error 
```
absl.flags._exceptions.DuplicateFlagError: The flag 'jax_omnistaging' is defined twice. First from jax.config, Second from jax.config.  Description from first occurrence: Deprecated. Setting this flag to False raises an error. Setting it to True has no effect.
```

I think the issue is probably in https://github.com/deepmind/launchpad/blob/master/launchpad/nodes/python/flags_utils.py#L54, I think there should be additional checks the function is first called to see if the flags have already been configured by the user.

**Comment by qstanczyk** [comment]
Thanks for reporting this issue.
Sent a pull request to JAX to fix this: https://github.com/google/jax/pull/6640
Also made a temp. fix to Launchpad, pending review.

**Comment by qstanczyk** [comment]
Please reopen if you still see the issue.
