### ISSUE TITLE
Distributed processes on multiple machines with launchpad?

### ISSUE THREAD

**Issue by Idate96** [deepmind/launchpad#7]
Hi I was wondering if there was timeline for the release of the version that will support multiple processes on *multiple* machines. I am working with acme and that would be really cool!

**Comment by qstanczyk** [comment]
Hi Lorenzo, we are working on open sourcing such setup, but can't promise any dates yet.

**Comment by huangshiyu13** [comment]
> Hi I was wondering if there was timeline for the release of the version that will support multiple processes on _multiple_ machines. I am working with acme and that would be really cool!

We implement a distributed version of launchpad. Please check it here: [https://github.com/TARTRL/TLaunch](https://github.com/TARTRL/TLaunch)

**Comment by qstanczyk** [comment]
Actually - we have open-sources support for launching Launchpad programs on GCP some time ago - please have a look [here](https://github.com/deepmind/launchpad/blob/07f9a5deb7c81a7aa0a1dcd9f91d659f59d91452/launchpad/context.py#L45) for details. 

@huangshiyu13 - this is a great news. Would you be interested in adding your implementation to the Launchpad repository as one of the supported runtimes? That way any Launchpad user would be able to benefit from your runtime without any changes / awareness of your project existence.

**Comment by huangshiyu13** [comment]
> Actually - we have open-sources support for launching Launchpad programs on GCP some time ago - please have a look [here](https://github.com/deepmind/launchpad/blob/07f9a5deb7c81a7aa0a1dcd9f91d659f59d91452/launchpad/context.py#L45) for details.
> 
> @huangshiyu13 - this is a great news. Would you be interested in adding your implementation to the Launchpad repository as one of the supported runtimes? That way any Launchpad user would be able to benefit from your runtime without any changes / awareness of your project existence.

I'd like to add our implementation into launchpad. But I have no idea how can I do it.

**Comment by vaxenburg** [comment]
Hi guys, any news on open-sourcing multiple machine support, by any chance?

**Comment by qstanczyk** [comment]
It is available - see [here](https://github.com/deepmind/launchpad/blob/a60da5d920ab8cbf2d9ff6c401baf49bfceff3a2/launchpad/context.py#L45).

**Comment by vaxenburg** [comment]
Thanks @qstanczyk! I was wondering about using `launchpad` across multiple machines on a local cluster. Any plans on this front, by chance?
